// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type {
  StoryblokRichtext,
  StoryblokMultiasset,
  StoryblokMultilink,
  StoryblokAsset,
} from "../storyblok.d.ts";
export interface AppConfig {
  nav_main?: NavItem[];
  nav_actions?: ButtonItem[];
  nav_footer?: NavItem[];
  facebook?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  instagram?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  app_title: string;
  app_logo?: StoryblokAsset;
  seo?: Metatags[];
  component: "app-config";
  _uid: string;
  [k: string]: unknown;
}

export interface ButtonItem {
  icon?: unknown;
  hide_label?: boolean;
  variant?: number | string;
  size?: number | string;
  link: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  label?: string;
  block?: boolean;
  trailing_icon?: boolean;
  component: "button-item";
  _uid: string;
  [k: string]: unknown;
}

export interface CardItem {
  title?: string;
  description?: string;
  content?: string;
  variant?: number | string;
  actions?: ButtonItem[];
  component: "card-item";
  _uid: string;
  [k: string]: unknown;
}

export interface CustomSection {
  body?: StoryblokRichtext;
  component: "custom-section";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqItem {
  title: string;
  content: string;
  component: "faq-item";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqSection {
  questions?: FaqItem[];
  component: "faq-section";
  _uid: string;
  [k: string]: unknown;
}

export interface GridItem {
  medium?: unknown;
  col_span_md?: string;
  row_span_md?: string;
  large?: unknown;
  col_span_lg?: string;
  row_span_lg?: string;
  body?: (
    | AppConfig
    | ButtonItem
    | CardItem
    | CustomSection
    | FaqItem
    | FaqSection
    | GridItem
    | GridSection
    | IconItem
    | LogosSection
    | Metatags
    | NavItem
    | PageDefault
    | PageHeader
    | PageHero
    | PageSection
  )[];
  component: "grid-item";
  _uid: string;
  [k: string]: unknown;
}

export interface GridSection {
  gap?: "" | "gap-4" | "gap-6" | "gap-8";
  medium?: unknown;
  cols_md?: string;
  justify_items_md?: number | string;
  justify_content_md?: number | string;
  align_items_md?: number | string;
  align_content_md?: number | string;
  large?: unknown;
  cols_lg?: string;
  justify_items_lg?: number | string;
  justify_content_lg?: number | string;
  align_items_lg?: number | string;
  align_content_lg?: number | string;
  body?: (
    | ButtonItem
    | CardItem
    | FaqItem
    | GridItem
    | IconItem
    | Metatags
    | NavItem
    | CustomSection
    | FaqSection
    | GridSection
    | LogosSection
  )[];
  component: "grid-section";
  _uid: string;
  [k: string]: unknown;
}

export interface IconItem {
  icon: unknown;
  size?: string;
  component: "icon-item";
  _uid: string;
  [k: string]: unknown;
}

export interface LogosSection {
  logos?: StoryblokMultiasset;
  component: "logos-section";
  _uid: string;
  [k: string]: unknown;
}

export interface Metatags {
  title?: string;
  description?: string;
  og_title?: string;
  og_description?: string;
  og_image?: StoryblokAsset;
  x_title?: string;
  x_description?: string;
  x_image?: StoryblokAsset;
  component: "metatags";
  _uid: string;
  [k: string]: unknown;
}

export interface NavItem {
  link: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  label?: string;
  children?: NavItem[];
  component: "nav-item";
  _uid: string;
  [k: string]: unknown;
}

export interface PageDefault {
  body?: (PageHeader | PageHero | PageSection)[];
  seo?: Metatags[];
  component: "page-default";
  _uid: string;
  [k: string]: unknown;
}

export interface PageHeader {
  title: string;
  description?: string;
  image?: StoryblokAsset;
  show_breadcrumb?: boolean;
  component: "page-header";
  _uid: string;
  [k: string]: unknown;
}

export interface PageHero {
  headline?: string;
  description?: string;
  image?: StoryblokAsset;
  buttons?: (
    | AppConfig
    | ButtonItem
    | CardItem
    | CustomSection
    | FaqItem
    | FaqSection
    | GridItem
    | GridSection
    | IconItem
    | LogosSection
    | Metatags
    | NavItem
    | PageDefault
    | PageHeader
    | PageHero
    | PageSection
  )[];
  component: "page-hero";
  _uid: string;
  [k: string]: unknown;
}

export interface PageSection {
  orientation?: "" | "vertical" | "horizontal";
  vertical_alignment?: "" | "start" | "center" | "end";
  background?: number | string;
  is_reversed?: boolean;
  title?: string;
  description?: string;
  content?: StoryblokRichtext;
  media?: StoryblokAsset;
  body?: (CustomSection | FaqSection | GridSection | LogosSection)[];
  actions?: ButtonItem[];
  has_border?: ("" | "border-t" | "border-b")[];
  component: "page-section";
  _uid: string;
  [k: string]: unknown;
}
